### ISSUE TITLE
Is there no GPU call

### ISSUE THREAD

**Issue by jxhxgt** [Aeonss/BubbleBlaster#14]

**Comment by jxhxgt** [comment]
![AA4635253D9D36FEA1B2C639E193A2BD](https://github.com/Aeonss/BubbleBlaster/assets/116073513/bd7d075b-c7f0-48c7-8ce9-ccfe3e0a2ef2)

**Comment by Aeonss** [comment]
> ![AA4635253D9D36FEA1B2C639E193A2BD](https://user-images.githubusercontent.com/116073513/281073847-bd7d075b-c7f0-48c7-8ce9-ccfe3e0a2ef2.png)

You'll need to install CUDA, check the installation here: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
