### ISSUE TITLE
Python Crash

### ISSUE THREAD

**Issue by Alex663366** [Aeonss/BubbleBlaster#19]
So the crash actually happened right after I hit the 'Blast' button. I'm not sure what the error was because I didn't see any signs. But what I do know is, when I executed the blast, Python stopped responding and eventually crashed. By the way, I'm not using a GPU.

**Comment by Aeonss** [comment]
Did the command prompt that is launched with the application say anything?

**Comment by Alex663366** [comment]
I didn't see anything else besides the message 'Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.' Then, it crashed after a few seconds. I've tried all versions of BubbleBlaster but the outcome remains the same. The only exception is when I use BubbleBlaster 1.2.2 NON-COMPACT, which displays the following message :

```
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000013E8219A520>.
  warnings.warn(
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000013E8219B4C0>.
  warnings.warn(
```

**Comment by Aeonss** [comment]
Looks like its a image issue. What's the image name? Can you send it here so I can test it?

**Comment by Alex663366** [comment]
Here
![002](https://github.com/Aeonss/BubbleBlaster/assets/150733797/46421f8e-0774-4d68-937b-34e4de08cc85)

**Comment by Alex663366** [comment]
![002](https://github.com/Aeonss/BubbleBlaster/assets/150733797/b037537a-da0d-44a0-a82c-a1e23e4a404c)

**Comment by Alex663366** [comment]
The name of the file is '001.png'

**Comment by Aeonss** [comment]
Hmm, it works on my end. Not sure why its not working for you. What are your computer specs?

**Comment by Alex663366** [comment]
i3 6100
8gb ram
no gpu

**Comment by Aeonss** [comment]
Hmm, can you download the entire repository and run the python file manually?

git clone https://github.com/Aeonss/BubbleBlaster

cd into the folder

run the command "python bubbleblaster.py"

See if that still crashes the program.

**Comment by Alex663366** [comment]
It keeps crashing, but I think it's because I didn't fulfill the requirements in the requirements.txt file.

**Comment by Alex663366** [comment]
After I installed the requirements and then ran the command 'python bubbleblaster.py', this is what appeared: 

```
import customtkpip install torchinter as ctk
                       ^
SyntaxError: invalid syntax
```

**Comment by Alex663366** [comment]
Do you have a recommended version of Python?

**Comment by Aeonss** [comment]
I'm using Python 3.11.1

**Comment by Alex663366** [comment]
I think the problem lies in the specifications of my own PC, it's quite unfortunate, but I appreciate you for answering all this time. I will be closing this post later.

**Comment by Aeonss** [comment]
Sorry, to hear this, 🙏🙏
