### ISSUE TITLE
Can not install it because easyocr

### ISSUE THREAD

**Issue by DiMiTriFrog** [Aeonss/BubbleBlaster#2]
I'm having this issue:

      ERROR: No matching distribution found for numpy==1.21.2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

I'm using python3.11.2 and numpy = 1.24.2

**Comment by Aeonss** [comment]
Try one of these solutions: https://stackoverflow.com/questions/66182906/error-no-matching-distribution-found-for-numpy-when-deploying-app-to-heroku

I'm not exactly sure how to solve it, since it seems to be an issue related to EasyOCR. If anything I would try to uninstall numpy and reinstall it.

**Comment by Aeonss** [comment]
Code has been rewritten, try cloning the project and reinstalling the requirements.
