### ISSUE TITLE
Feature request: terminal/cli use

### ISSUE THREAD

**Issue by arthurwolf** [Aeonss/BubbleBlaster#20]
I'd really like to be able to use this in the terminal instead of using a GUI. How difficult would that be?

If you can give instructions on how you'd implement it, I can try to do that work myself (and do a PR once done)

Thanks!

**Comment by Aeonss** [comment]
I've created a simple CLI in the 1.2.2 releases here https://github.com/Aeonss/BubbleBlaster/releases/tag/1.2.2

Let me know if you encounter any issues.

The command is

bb [path]

If you need more help, bb -h will tell you what to do.

**Comment by arthurwolf** [comment]
Thank you so much! Will test soon.
