### ISSUE TITLE
Bubble speechs languages and suggestion

### ISSUE THREAD

**Issue by wolverine4277** [Aeonss/BubbleBlaster#22]
It would be helpful to me if the Italian and spanish languages could be added.
On the other hand, an improvement could be to allow to select also the language to which you want to translate.
A question, is there any tool that I can download to generate an executable from the script? Or is it necessary to have Python installed? I ask because I do not use Python but this tool would be very useful!
Best regards.

**Comment by wolverine4277** [comment]
I finally downloaded the script and started playing with it.
I added the languages I needed (translation from English to Spanish and from Italian to Spanish) and tried with some images. So far the only thing I notice is that when a text starts with ... it doesn't recognize it, at least with the images I used. Have you had any case like this?
I try removing the ... and the result was the same. The original text was "... REVENGE IS INDEED SWEET!"
![imagen](https://github.com/Aeonss/BubbleBlaster/assets/7396741/2686f449-ba24-4b96-93e6-e4fb32554a1a)

**Comment by Aeonss** [comment]
> It would be helpful to me if the Italian and spanish languages could be added. On the other hand, an improvement could be to allow to select also the language to which you want to translate. A question, is there any tool that I can download to generate an executable from the script? Or is it necessary to have Python installed? I ask because I do not use Python but this tool would be very useful! Best regards.

You would need python installed. To generate an executable, you'd need [pyinstaller](https://pyinstaller.org/en/stable/).

**Comment by Aeonss** [comment]
> I finally downloaded the script and started playing with it. I added the languages I needed (translation from English to Spanish and from Italian to Spanish) and tried with some images. So far the only thing I notice is that when a text starts with ... it doesn't recognize it, at least with the images I used. Have you had any case like this? I try removing the ... and the result was the same. The original text was "... REVENGE IS INDEED SWEET!" ![imagen](https://private-user-images.githubusercontent.com/7396741/294929848-2686f449-ba24-4b96-93e6-e4fb32554a1a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Mjc1OTgsIm5iZiI6MTcwNDcyNzI5OCwicGF0aCI6Ii83Mzk2NzQxLzI5NDkyOTg0OC0yNjg2ZjQ0OS1iYTI0LTRiOTYtOTNlNi1lNGZiMzI1NTRhMWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTUyMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FlYjRiYTk1NTNiYWIwZmMyZWJkY2NhZmYxM2VkZGY2NDhkZjQ4NjY3OGFhMTE2N2Y3YmJlOGIwZDE0MzRkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LeXQlM0LYQkKWvZYIs6PNBmngn5h9kgbbhIFYFkBOvQ)

The program is mostly for korean translations, but I'll add a X translation. Although, the translation feature is more of a testing thing and not really meant to be used. The model finds it hard for punctuation, so it would make sense why it doesn't detect it. Can you upload the original image so I can test it out myself?

**Comment by wolverine4277** [comment]
> > I finally downloaded the script and started playing with it. I added the languages I needed (translation from English to Spanish and from Italian to Spanish) and tried with some images. So far the only thing I notice is that when a text starts with ... it doesn't recognize it, at least with the images I used. Have you had any case like this? I try removing the ... and the result was the same. The original text was "... REVENGE IS INDEED SWEET!" ![imagen](https://private-user-images.githubusercontent.com/7396741/294929848-2686f449-ba24-4b96-93e6-e4fb32554a1a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Mjc1OTgsIm5iZiI6MTcwNDcyNzI5OCwicGF0aCI6Ii83Mzk2NzQxLzI5NDkyOTg0OC0yNjg2ZjQ0OS1iYTI0LTRiOTYtOTNlNi1lNGZiMzI1NTRhMWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTUyMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FlYjRiYTk1NTNiYWIwZmMyZWJkY2NhZmYxM2VkZGY2NDhkZjQ4NjY3OGFhMTE2N2Y3YmJlOGIwZDE0MzRkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LeXQlM0LYQkKWvZYIs6PNBmngn5h9kgbbhIFYFkBOvQ)
> 
> The program is mostly for korean translations, but I'll add a X translation. Although, the translation feature is more of a testing thing and not really meant to be used. The model finds it hard for punctuation, so it would make sense why it doesn't detect it. Can you upload the original image so I can test it out myself?

Hello, thank you for the prompt reply.
This is the original image. I tried decreasing the confidence but it does not detect them.
Anyway what I find more useful is the functionality to remove the texts inside the bubbles.

![original](https://github.com/Aeonss/BubbleBlaster/assets/7396741/6321bd97-9a23-41a5-a087-b6d8f2643265)

**Comment by Aeonss** [comment]
Yeah, the  ... is so far away from the text that it doesn't recognize it. Although, my program detects the "revenge is sweet part"

![1](https://github.com/Aeonss/BubbleBlaster/assets/30298077/e3b5317f-5478-46ef-a422-a7845945edee)

![294956908-6321bd97-9a23-41a5-a087-b6d8f2643265_ocr](https://github.com/Aeonss/BubbleBlaster/assets/30298077/02015013-734b-4fcd-915b-b908a1c51ae0)

**Comment by wolverine4277** [comment]
Yes, I noticed that when it does not detect some text, you can lower the confidence level so that it recognizes it.
Thank you very much!

**Comment by Aeonss** [comment]
Added Spanish and Italian in v1.2.3
