### ISSUE TITLE
Selection of OCR boxes 

### ISSUE THREAD

**Issue by Imanpreet96** [Aeonss/BubbleBlaster#27]
Hi ,
I want to remove only some text parts instead of all , I already have co-ordinates for the OCR boxes I would like to remove from images, can you please tell what changes do we make to apply it
![image](https://github.com/Aeonss/BubbleBlaster/assets/159404342/29c05369-dcd7-4654-b91a-a5d45a2d8296)

**Comment by Aeonss** [comment]
Added in 2.0
