### ISSUE TITLE
Can't Open The Program

### ISSUE THREAD

**Issue by RexGhidorah** [Aeonss/BubbleBlaster#30]
Maybe i´m not doing something right, but i downloaded the latest release and when i try to open it just pops up a CMD window for half a second and then closes. Just that :,^

**Comment by RexGhidorah** [comment]
I managed to take a screenshot, how can I solve it? :,D
![Captura de pantalla (145)](https://github.com/Aeonss/BubbleBlaster/assets/168611490/701c38e0-1d22-418a-8bdc-2ee59c6af93b)

**Comment by Aeonss** [comment]
You downloaded the CLI version. Download from https://github.com/Aeonss/BubbleBlaster/releases/download/1.2.4/bubbleblaster-v1.2.4.exe instead.
