### ISSUE TITLE
It is not working, how I can use this

### ISSUE THREAD

**Issue by charlie-bikelife** [Aeonss/BubbleBlaster#33]
I installed your program, but does not initialize 
How I can use ?

**Comment by charlie-bikelife** [comment]
just show
![Uploading 20240623_132359.jpg
![20240623_132359](https://github.com/Aeonss/BubbleBlaster/assets/173589235/84336f86-4692-4022-90a4-0dfb91fe8ce1)
()

**Comment by charlie-bikelife** [comment]
Actually, I used python 3.10.11 version and failed... also installed latest version again and also failed.... I guess this program has some problem. Wish I could use this program! please help~

**Comment by Aeonss** [comment]
Try the latest version

**Comment by charlie-bikelife** [comment]
Thank you so much!

김재형

Email : ***@***.***

Mobile : 010-2741-6834

씨케이공일공삼(CK0103)

-----Original Message-----

**Comment by charlie-bikelife** [comment]
hi there is no exe file to activate the program!!! please let me know how I can use?

감사합니다.


김재형

Email : ***@***.***

Mobile : 010-2741-6834

씨케이공일공삼(CK0103)

-----Original Message-----

**Comment by Aeonss** [comment]
> hi there is no exe file to activate the program!!! please let me know how I can use? 감사합니다. 김재형 Email : ***@***.*** Mobile : 010-2741-6834 씨케이공일공삼(CK0103)
> […](#)
> -----Original Message----- From: ***@***.***> To: ***@***.***>; Cc: ***@***.***>; ***@***.***>; Sent: 2024-08-05 (월) 11:54:18 (GMT+09:00) Subject: Re: [Aeonss/BubbleBlaster] It is not working, how I can use this (Issue #33) Closed #33 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Use the "run.bat"

**Comment by charlie-bikelife** [comment]
I tried bubbleblaster lastest version. there is .bat file. However, it does not work. can not execute the file


감사합니다.


김재형

Email : ***@***.***

Mobile : 010-2741-6834

씨케이공일공삼(CK0103)

-----Original Message-----

**Comment by Aeonss** [comment]
> I tried bubbleblaster lastest version. there is .bat file. However, it does not work. can not execute the file 감사합니다. 김재형 Email : ***@***.*** Mobile : 010-2741-6834 씨케이공일공삼(CK0103)
> […](#)
> -----Original Message----- From: ***@***.***> To: ***@***.***>; Cc: ***@***.***>; ***@***.***>; Sent: 2024-08-05 (월) 11:54:21 (GMT+09:00) Subject: Re: [Aeonss/BubbleBlaster] It is not working, how I can use this (Issue #33) Try the latest version — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>


Try the newest 2.0.1 version first, see if that works. Run the "INSTALL_DEPENDENCIES.bat" first and then the "bubbleblaster.bat"

**Comment by Aeonss** [comment]
I included a exe version... try if it doesn't work

**Comment by charlie-bikelife** [comment]
Always thank you for your support!

However, when I execute your profile, it shows the dos window for 1 second, and then just disappear...
I guess there is some problem! Anyway thank you and I think I need to find out other solutions!

Thank you!


-----Original Message-----
