### ISSUE TITLE
I've this error

### ISSUE THREAD

**Issue by bigipiex** [Aeonss/BubbleBlaster#35]
I ran pip install -r requirements.txt
and python bubbleblaster.py
![Tabby_FgAkxEaTi6](https://github.com/user-attachments/assets/1fe4c910-4f26-4720-b72e-40242d3cb17b)

**Comment by Aeonss** [comment]
Try the newest 2.0.1 version first, see if that works. Run the "INSTALL_DEPENDENCIES.bat" first and then the "bubbleblaster.bat"

**Comment by Aeonss** [comment]
I included a exe version... try if it doesn't work

**Comment by bigipiex** [comment]
> I included a exe version... try if it doesn't work

I found the problem, you need to put this dll on system32 in windows11

https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
