### ISSUE TITLE
New version has broken dependencies? Numpy

### ISSUE THREAD

**Issue by tillx100** [Aeonss/BubbleBlaster#36]
I made a new Conda environment using python 3.11.9 and the installation of dependencies fails.

 Preparing metadata (pyproject.toml) ... done
ERROR: Cannot install -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 6), -r requirements.txt (line 7), matplotlib and numpy==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==2.0.1
    easyocr 1.7.1 depends on numpy
    matplotlib 3.9.1.post1 depends on numpy>=1.23
    opencv-python 4.10.0.84 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.10.0.84 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python 4.10.0.84 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.10.0.84 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.10.0.84 depends on numpy>=1.19.3; python_version >= "3.9"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.19.3; python_version >= "3.9"
    contourpy 1.2.0 depends on numpy<2.0 and >=1.20
    The user requested numpy==2.0.1
    easyocr 1.7.1 depends on numpy
    matplotlib 3.9.1.post1 depends on numpy>=1.23
    opencv-python 4.10.0.84 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.10.0.84 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python 4.10.0.84 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.10.0.84 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.10.0.84 depends on numpy>=1.19.3; python_version >= "3.9"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python-headless 4.10.0.84 depends on numpy>=1.19.3; python_version >= "3.9"
    contourpy 1.1.1 depends on numpy<2.0 and >=1.16; python_version <= "3.11"

**Comment by Aeonss** [comment]
Do pip uninstall numpy and then reinstall numpy 1.26.4

**Comment by Aeonss** [comment]
Run the "INSTALL_DEPENDENCIES.bat" and then the "BUBBLEBLASTER.BAT".

I included a exe version... try if it doesn't work

**Comment by bosskham** [comment]
before install dependencies Just delete numpy==2.0.1 from requirements.txt then run pip install -r requirements.txt
