### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by NinjaScoutZ** [Aeonss/BubbleBlaster#8]
Downloading detection model, please wait. This may take several minutes depending upon your network connection.
Progress: |██████████████████████████████████████████████████| 100.0% CompleteDownloading recognition model, please wait. This may take several minutes depending upon your network connection.
Progress: |██████████████████████████████████████████████████| 100.0% CompleteException in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dansa\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\dansa\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 456, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "C:\Users\dansa\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 379, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "C:\Users\dansa\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\utils.py", line 540, in get_image_list
    maximum_y,maximum_x = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Aeonss** [comment]
Hmm I thought I had fixed this. What is your image file name? Remove any non utf-8 characters.

**Comment by NinjaScoutZ** [comment]
its just like a number 01.png 02.png like that

**Comment by Aeonss** [comment]
Send me the image and I'll take a look at it

**Comment by NinjaScoutZ** [comment]
![02(1)](https://user-images.githubusercontent.com/132326611/235603858-1419c3ad-8361-496e-a4ec-e4080abc7d72.png)

**Comment by Aeonss** [comment]
Works for me, do you have the latest version of BubbleBlaster?

**Comment by NinjaScoutZ** [comment]
yep its latest version

**Comment by bato3** [comment]
Any non ascii char in PATH? Or long PATH?

**Comment by Aeonss** [comment]
> Any non ascii char in PATH? Or long PATH?

Directory path

**Comment by Aeonss** [comment]
Try the latest release, let me know if you still have this issue
